default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: base-rails-tools_development

test:
  <<: *default
  database: base-rails-tools_test

production:
  <<: *default
  database: base-rails-tools_production
  username: base-rails-tools
  password: <%= ENV['BASE-RAILS-TOOLS_DATABASE_PASSWORD'] %>

